### ISSUE TITLE
Specify packages, unpacker script(?)

### ISSUE THREAD

**Issue by MrReplikant** [mishalew1/apt_offline#1]
Hello there,
are there plans to modify this script to where you can specify what packages you want? That would be amazing

Also, are there plans for  a script that can install it on another machine? 

Just wondering

**Comment by mishalew1** [comment]
> Hello there,
> 
> are there plans to modify this script to where you can specify what packages you want? That would be amazing
> 
> 
> 
> Also, are there plans for  a script that can install it on another machine? 
> 
> 
> 
> Just wondering

Any package added to the list named "package_list" will get downloaded along with all its recursive dependencies. 
Will likely make another script which can install it on another machine.

**Comment by MrReplikant** [comment]
Excellent, I look forward to your installation script
